### ISSUE TITLE
Using the batch API returns 500 for certain paper ids 

### ISSUE THREAD

**Issue by ggasteratos** [allenai/s2-folks#103] opened 2023-05-22 08:51 UTC
Hi all,

I am trying to get details for multiple papers at once using the https://api.semanticscholar.org/graph/v1/paper/batch API.
If the ids I am passing in contain this id cebe6f46f49d8c466d158e4663ccaa0bdfa48a86 it returns 500. The number of ids I am passing in is 5. If I exclude this particular id from the request it works fine.

Accessing the same id with the normal API it works fine. https://api.semanticscholar.org/graph/v1/paper/cebe6f46f49d8c466d158e4663ccaa0bdfa48a86 

Please advise...

Thanks in advance,
Greg

**Comment by ggasteratos** [comment] 2023-05-22 14:27
It might be helpful to mention that I am trying to get back the following fields:
openAccessPdf,isOpenAccess,externalIds,year,title,authors,publicationDate,url,tldr,venue,referenceCount,citationCount,authors.paperCount,authors.name,authors.aliases

**Comment by AmberRose2** [comment] 2023-06-27 18:40
Hi Greg,

Thanks for pointing out this issue! The root cause was a bug on our end that occurred when an author doesn't have an Id in the bulk endpoint. 
I'm happy to report that the bug has been fixed now, so you should no longer see an issue with this request.

Cheers!

**Closed by AmberRose2** 2023-06-27 18:40 UTC
