### ISSUE TITLE
Performing exact paper title search

### ISSUE THREAD

**Issue by EthanC111** [allenai/s2-folks#43] opened 2023-03-31 03:09 UTC
Can Semantic Scholar API perform an exact paper title search? I discovered that while I can obtain relevant results by conducting an exact title search on the Semantic Scholar website (https://www.semanticscholar.org/), the same is not possible through the API search (https://www.semanticscholar.org/product/api).

**Comment by wammar** [comment] 2023-04-04 00:19
Duplicate of https://github.com/allenai/s2-folks/issues/32

Marking as duplicate to indicate importance and reduce # of issues tracked.

**Closed** 2023-04-04 00:19 UTC
