### ISSUE TITLE
Fail to search NeurIPS papers

### ISSUE THREAD

**Issue by xvjiarui** [allenai/s2-folks#114] opened 2023-06-15 13:41 UTC
**Describe the bug**
Since Neural Information Processing Systems changed the name from NIPS to NeurIPS, the search on NeurIPS paper breaks before the name changing for both the venues. 

**To Reproduce**
`https://api.semanticscholar.org/graph/v1/paper/search?query=A%20memory%20frontier%20for%20complex%20synapses&fields=paperId,corpusId,url,title,venue,externalIds&venue=NIPS,NeurIPS,Neural%20Information%20Processing%20Systems&limit=100&offset=0` didn't return any papers with limitation on venue. But if we remove the `venue` by calling `https://api.semanticscholar.org/graph/v1/paper/search?query=A%20memory%20frontier%20for%20complex%20synapses&fields=paperId,corpusId,url,title,venue,externalIds&limit=100&offset=0`, it returns
```
{
      "paperId": "75c7ec96aaa5d271d541466e5d5a7807e815b488",
      "externalIds": {
        "DBLP": "conf/nips/LahiriG13",
        "MAG": "2110563098",
        "CorpusId": 616640
      },
      "corpusId": 616640,
      "url": "https://www.semanticscholar.org/paper/75c7ec96aaa5d271d541466e5d5a7807e815b488",
      "title": "A memory frontier for complex synapses",
      "venue": "NIPS"
    },
```
**Expected behavior**
The api should be able to return this paper with venue constraint. 

Truly appreciate any help or suggestion.

**Comment by cfiorelli** [comment] 2023-09-11 02:17
Confirming observed behavior here. 
Any variation containing venue=NeurIPS returns no results yet without venue or with venue=NIPS returns as expected: 

{"total": 16, "offset": 0, "next": 10, "data": [{"paperId": "75c7ec96aaa5d271d541466e5d5a7807e815b488", "title": "A memory frontier for complex synapses"}, {"paperId": "6b20b975e68900bf90b97a48c0fd73c847abb780", "title": "XIth Cajal Conference: New frontiers in neuron\u2010glial plasticity in health and disease"}, {"paperId": "eeace6046fa5f86a142222562269af14b9f6b363", "title": "Complex oxides for brain-inspired computing: A review."}, {"paperId": "653e4ad2bfd2dcb9932c76362397fe6c1d5f999c", "title": "Editorial: Network physiology, insights into the brain system: 2021"}, {"paperId": "bc45992dcf526961c63e0b9060a79daac15ea29d", "title": "Frontiers in Computational Neuroscience"}, {"paperId": "847e93a1616648acea60aeb58e7f1c2f70682b74", "title": "Cellular bases of behavioral plasticity: establishing and modifying synaptic circuits in the Drosophila genetic system."}, {"paperId": "c8930ae43eb05ab2d00e1b93595be0f1b6c73180", "title": "Guest editorial: Special issue on neuroimaging"}, {"paperId": "7d717ab3031efee33ce0f81e7dd0846802457903", "title": "ALLOSTERIC REGULATION OF SYNAPTIC PROCESSES THESIS FOR DOCTORAL DEGREE ( Ph . D . ) By Ranjita"}, {"paperId": "6a094e2c55d6866485f357d0e3b761f341eef5bb", "title": "Editorial: Breaking the cycle: attacking the malaria parasite in the liver"}, {"paperId": "5c52fc5a44c5da6b65ea145f0c6944d44879df49", "title": "New Challenges and Frontiers in the Research for Neuropsychiatric Disorders"}]}

**Comment by smitar** [comment] 2023-10-10 18:18
Likely an error in s2ove, venue normalization

**Comment by power10dan** [comment] 2023-10-10 18:42
There is a ticket for this: https://github.com/allenai/scholar/issues/38680, and I'm working on it.

**Comment by smitar** [comment] 2023-10-10 18:48
Thanks @power10dan. Closing as duplicate of https://github.com/allenai/scholar/issues/38680.

**Closed by smitar** 2023-10-10 18:48 UTC

**Comment by power10dan** [comment] 2023-10-11 06:29
So I tried reproducing the error. Here is the result where I specified the publicationVenue field in the API:
```json
"paperId": "75c7ec96aaa5d271d541466e5d5a7807e815b488", "externalIds": {"MAG": "2110563098", "DBLP": "conf/nips/LahiriG13", "CorpusId": 616640}, "corpusId": 616640, "publicationVenue": null, "url": "https://www.semanticscholar.org/paper/75c7ec96aaa5d271d541466e5d5a7807e815b488", "title": "A memory frontier for complex synapses", "venue": "NIPS"}
```
Looks like the publicationVenue is null, which might suggest that this paper is one of the few exceptions where we do not have a normalized venue name to it. I think doing a backfill on this paper should work? I've added NIPS as an alternative name to the NeurIPS venue, so we should make this paper have a normalized venue name.

**Comment by cfiorelli** [comment] 2023-10-11 20:31
@xvjiarui  try again your original request should now return the expected result

**Comment by power10dan** [comment] 2023-10-11 21:08
Fixed in https://github.com/allenai/scholar/issues/38680.
