### ISSUE TITLE
How to verify my API key works as intended?

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#6] opened 2023-03-13 21:52 UTC
> I’m getting an error code 403 back from the API when using my api key with the following headers:
>   "headers": {
>     "Content-type": "application/json",
>     "x-api-key": my_precious_key
>   },
> it looks like I am sending it correctly, but somehow I’m getting a Forbidden 403 back… Am I missing something?

From slack.

**Comment by jdwuarin** [comment] 2023-03-14 17:37
This was reported by me for reference (my name might help you find the information about my specific API key in your system if the issue is somehow linked to that).

**Comment by jdwuarin** [comment] 2023-03-20 17:35
I ended up requesting a new API key that works - I've discarded the one that doesn't work, feel free to close this issue now

**Comment by wammar** [comment] 2023-04-08 15:27
Thanks for your patience @jdwuarin; We've been making some changes to our internal processes and some of the API key requests fell through the cracks.

**Comment by wammar** [comment] 2023-04-08 15:37
Feature request: add a script to https://github.com/allenai/s2-folks for partners to verify that their API key actually works to access authentication-only endpoints (without testing the rate limit).

**Closed** 2023-08-18 00:20 UTC
Labels: enhancement, status:open/roadmap
