### ISSUE TITLE
S2 paperId for S2ORC papers

### ISSUE THREAD

**Issue by sMamooler** [allenai/s2-folks#10] opened 2023-03-15 17:26 UTC
Hello, 
Is there a way to have the S2 id (`paperId` field) for the papers in S2ORC? The `corpus_id` seems to be the id specific to S2ORC and is not the same as the S2 id associated to all papers that can be found using keyword search in the API.

Thanks!

**Comment by wammar** [comment] 2023-03-21 11:36
Thanks for the question @sMamooler! I'm looking into this now. Also, let me merge this with a similar question.

**Comment by wammar** [comment] 2023-03-21 11:37
Duplicate of #11

**Comment by wammar** [comment] 2023-04-23 21:30
This was addressed in #11 but I forgot to provide the answer here as well:

You can use either ID to lookup the other using a query like this: https://api.semanticscholar.org/graph/v1/paper/649def34f8be52c8b66281af98ae884c09aef38b?fields=paperId,corpusId

**Closed by wammar** 2023-04-23 21:30 UTC
Labels: question, status:open/WIP

**Comment by rosnikv** [comment] 2023-05-25 09:46
@sMamooler  Did you find a solution to this? I currently have only corpusId for the s2orc papers, and I cannot retrieve paper details using the corpusId. For example, something similar,  `https://api.semanticscholar.org/graph/v1/paper/19170988?fields=paperId`
