### ISSUE TITLE
How to download dataset

### ISSUE THREAD

**Issue by Zivenzhu** [allenai/s2-folks#21] opened 2023-03-23 15:07 UTC
I am sorry that I am confronted with some difficulties. I mean I am at a loss of what to do after reading the readme files of how to download the dataset.

**Comment by 37david** [comment] 2023-03-23 15:10
![image](https://user-images.githubusercontent.com/95232487/227247499-82dec378-701e-4e3a-84fc-cd25857b9455.png)

**Comment by 37david** [comment] 2023-03-23 15:10
![image](https://user-images.githubusercontent.com/95232487/227247679-ebe3c1b2-57df-4da6-9487-df17cf9762d0.png)

**Comment by 37david** [comment] 2023-03-23 15:13
I just run the codes but it seems that nothing happens in my directory. And the feedback in the python controlling desk seems hard to read.

**Comment by 37david** [comment] 2023-03-23 15:15
Then I just try to log on to second website listed above to download the s2ag.py manually. But things happen when I am running the py file.

**Comment by 37david** [comment] 2023-03-23 15:19
![image](https://user-images.githubusercontent.com/95232487/227250194-5f283ff2-2a80-4e89-bde0-ce030478faa7.png)

**Comment by 37david** [comment] 2023-03-23 15:19
It seems that the papers can't be read beacuase I lack the api key

**Comment by 37david** [comment] 2023-03-23 15:22
papers = requests.get("http://api.semanticscholar.org/datasets/v1/release/latest/dataset/papers",headers={'x-api-key':os.getenv("S2_API_KEY")}).json()
In the lines above to be more specific.

However, after changing the "S2_API_KEY" into the api keys I received from the authority. It does not work.

**Comment by 37david** [comment] 2023-03-23 15:24
Sorry for troubling you for my problems. I am now just an undergraduate working on my project so I may be fresh in some practical issues. Your help will be highly appreciated!

**Comment by wammar** [comment] 2023-04-23 20:43
@37david I am sorry it took me so long to respond to this issue. We've made significant improvements to our documentation for all endpoints since you opened this issue, and we're working on more improvements. In particular, I'd like to point you to a [python script](https://github.com/allenai/s2-folks/pull/24/files#diff-c1c836ecbde0d07d1db90c65fd7f47e129c59f26a68f8f2bd26772cfaf249c65) (still under review) which shows how you can interact with the datasets available using the Semantic Scholar API.

**Comment by wammar** [comment] 2023-04-23 20:43
Duplicate of #31

**Closed** 2023-08-17 20:08 UTC
Labels: question, status:open/WIP
